### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by jawnsy** [miekg/exdns#10]
Dear maintainer,

Thanks for your awesome DNS library and accompanying examples!

I noticed the source code headers refer to a `LICENSE` file, but none is included in this repository.

Cheers,

Jonathan

**Comment by miekg** [comment]
indeed! These where once part of the godns, but they've split of. This should be a https://opensource.org/licenses/BSD-2-Clause

**Comment by jawnsy** [comment]
@miekg Should this just be a copy of https://github.com/miekg/dns/blob/master/LICENSE

I can submit a PR if that would help :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/exdns] Missing LICENSE f..." ]
>@miekg Should this just be a copy of https://github.com/miekg/dns/blob/master/LICENSE
>
>I can submit a PR if that would help :)

Yes please do :-) Except it does not need to the Google Authors.
Anyway just submit a PR I'll brush it up after #lazy

Thanks!

/Miek

--
Miek Gieben

**Comment by jawnsy** [comment]
Bah, sorry! Turns out I should've tested first, the license badge isn't working. Will fix in a follow-up PR.

Tested this time here: https://github.com/jawnsy/licensetest

(Seems to be a little finicky with the way the text is formatted)
