### ISSUE TITLE
Does this library cache support

### ISSUE THREAD

**Issue by mageddo** [miekg/exdns#13]
Hey, I wanna to know if this library supports cache, if no any suggestions of what to do? Thanks

**Comment by miekg** [comment]
No it doesn't you'll have to implement that yourself.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/exdns] Does this library cac..." ]
>Hey, I wanna to know if this library supports cache, if no any suggestions of what to do? Thanks

Also this is *not* the library, these are just a bunch of examples to show how
to use github.com/miekg/dns

**Comment by mageddo** [comment]
Thanks, yes I am talking about `github.com/miekg/dns` my fault for the wrong repository.
