### ISSUE TITLE
q won't compile because ErrTruncated is gone

### ISSUE THREAD

**Issue by miekg** [miekg/exdns#17]
ErrTruncated has been removed from the library, meaning `q` (and mabybe others here) won't compile anymore.

**Comment by miekg** [comment]
There is none. You have to inspect msg.Truncated for this

On 4 Dec 2018 23:26, "Gert Cuykens" <notifications@github.com> wrote:

I just wanted to create a ticket for that :D no idea what the new Error
type is

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/miekg/exdns/issues/17#issuecomment-444298834>, or mute
the thread

**Comment by gertcuykens** [comment]
I just removed the complete case block :p good enough for me

**Comment by ZLightning** [comment]
This issue is fixed by the above pull request so the issue can now be closed.
