### ISSUE TITLE
q: configurable TCP timeout?

### ISSUE THREAD

**Issue by JeremyRand** [miekg/exdns#20]
The TCP timeout in `q` is hardcoded to 2 seconds.  Would a PR that makes this configurable via a command-line flag be accepted?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/exdns] q: configurable TCP t..." ]
>The TCP timeout in `q` is hardcoded to 2 seconds.  Would a PR that makes this configurable via a command-line flag be accepted?

just look what dig does, PR sgtm
